# docker-compose.yaml
services:
  #   gui:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile.gui
  #     environment:
  #       DISPLAY: ${DISPLAY}
  #     network_mode: host
  #     volumes:
  #       - ${XAUTHORITY}:/root/.Xauthority
  #       - /tmp/.X11-unix:/tmp/.X11-unix
  #     devices:
  #       - "/dev/dri/card0:/dev/dri/card0"

  headless:
    container_name: hel_rallyrobot
    build:
      context: .
      dockerfile: Dockerfile.headless
    restart: no
    stdin_open: true                # Keep stdin open even if not attached
    tty: true                       # Allocate a pseudo-TTY
    volumes:
      - ./results:/app/results
